### ISSUE TITLE
HA ignores defined wud.display.icon 

### ISSUE THREAD

**Issue by huettenwirt** [fmartinou/whats-up-docker#282] opened 2023-05-08 16:17 UTC
Hi, 

not sure where the source of the behaviour is located, but the defined wud.display.icon (e.g. wud.display.icon: mdi:note-multiple) is ignored in HA since the move in WUD to the update entities (e.g. update.wud_container_local_paperless_webserver_1). 
Instead of the icon defined in the respective stack/docker-compose via wud.display.icon, Home Assistant shows a dark blue docker icon.
I also tried changing the icon of the entity in HA , but this is also ignored. 

I'm currently out of ideas where to look for the correct definition of the respective icons. Any idea from your end?

Best regards,
Huettenwirt

**Comment by fmartinou** [comment] 2023-05-16 20:40
Hi,

I think it's a duplicate of #194.

You should find there the reasons of this change.

**Closed** 2023-07-05 08:57 UTC
Labels: question
