### ISSUE TITLE
Enable Watch Digest by Default for Watcher

### ISSUE THREAD

**Issue by jeremywillans** [fmartinou/whats-up-docker#67] opened 2021-09-21 02:04 UTC
Is it possible to enable "digest watching" at a watcher level (ENV Variable) rather than needing to enable on each container?

**Comment by fmartinou** [comment] 2021-09-21 07:59
Hi,

It' not possible right now but it can be easily implemented.

I can implement a `WUD_WATCHER_{watcher_name}_WATCHDIGEST` env var (the default value will be `false`).
It will drive the default behaviour for containers without `wud.watch.digest` label.

On top of that, `wud.watch.digest` will still be evaluated to override this common behaviour per container.

Would that suit you?

**Comment by jeremywillans** [comment] 2021-09-21 08:25
@fmartinou That would be awesome!

Also, I have been testing the MQTT/HA integration and works an absolute treat! Is there however, any possibility of publishing the container state? 🤞

**Comment by fmartinou** [comment] 2021-09-21 08:34
Thanks !

> Is there however, any possibility of publishing the container state?

What do you really mean with `container state`?

- The HA integration creates binary entities whose state is `on|off` whether there is an update available.
- All other data collected wy WUD are published within the Mqtt payload and parsed by HA as entity attributes.

![image](https://user-images.githubusercontent.com/16061231/134138307-6149e855-6dac-4ecf-809c-fc996b5d8cb2.png)

**Comment by jeremywillans** [comment] 2021-09-21 08:36
Was specifically hoping for running/stopped just as a way of filtering results locally in HA

**Comment by jeremywillans** [comment] 2021-09-21 09:38
Done #68 (y)

**Comment by fmartinou** [comment] 2021-09-23 14:01
Can you give it a try?
`fmartinou/whats-up-docker:feature__67`

(please remove WUD state before if mounted as persistent volume)

**Comment by jeremywillans** [comment] 2021-09-23 22:35
Tested and working! 👍

**Comment by fmartinou** [comment] 2021-09-24 07:42
Nice! Will be part of the next release.

**Closed by fmartinou** 2021-09-24 07:42 UTC
Labels: enhancement

**Comment by fmartinou** [comment] 2021-09-24 08:29
Available in `5.7.0`

**Comment by jeremywillans** [comment] 2021-09-25 02:23
I seem to now be getting a new error with this setting enabled 😕


12:22:10.393  WARN whats-up-docker/registry: Some watchers failed to register (Error when registering component docker ("watchdigest" is not allowed))

**Comment by fmartinou** [comment] 2021-09-25 07:03
What tag are you running? `5.7.0`?

**Comment by jeremywillans** [comment] 2021-09-25 07:18
Yeah I think this is user error 🙄 .. however latest tag appears to be throwing an issue with status in the container model

**Comment by fmartinou** [comment] 2021-09-25 07:23
`latest` should be aligned with `5.7.0` so both the watchdigest config entry and the status property should be supported 

Maybe force the pull of the `latest` tag to be sure?

**Comment by jeremywillans** [comment] 2021-09-25 08:46
Hmm I have tried that and it’s still not working for me 😕 it’s working fine on 5.7.0 tho 🤷‍♂️

**Comment by fmartinou** [comment] 2021-09-25 09:21
Maybe there was an issue when building the `latest` tag :thinking: 
I take a look and I keep you informed.

**Comment by fmartinou** [comment] 2021-09-25 09:57
I cannot reproduce your issue with `latest`.

I tested moving from `5.7.0` to `latest` and back again (with and without keeping the `wud.json` file) and all is working fine (I mean no warnings in logs, `watchdigest=true` and container `status` working as expected).

**Comment by fmartinou** [comment] 2021-09-29 12:27
Hi @jeremywillans ,

Just to let you know: starting from version `5.8.0`, the env var `WUD_WATCHER_{watcher_name}_WATCHDIGEST` has been deprecated.

Actually, I changed the behavior so that **by default**:
- **digest watching is automatically enabled for containers with non semver image tags** (like`latest`)
- **digest watching stays disabled for containers with semver image tags**

So it should still suit your needs (enable digest watching on all your `latest` containers).

(by the way, it's still possible to customize this behavior per container using labels).

**Comment by TheQuantumPhysicist** [comment] 2025-07-27 15:54
I have to say that not have watch digest enabled by default for me is just way too destructive... I find myself forced to sprinkle the label `wud.watch.digest` all over the place, because if I don't, and I ever, ever use a tag that's not `latest`, WUD will just update to the latest version. 

An example where this is destructive, is Seafile. It just updated from 11-latest to 13.0.7-testing, destroying all my data in the process due to a faulty upgrade. Luckily I had incremental backups, so it just cost me a few hours of restoration.

But not having `WUD_WATCHER_{watcher_name}_WATCHDIGEST` as the default can just be way too destructive... ruining all containers, especially for new users. I just learned about WUD recently and my god, it did too much destruction because I'm an idiot who couldn't read the whole docs word for word and understand the effects... so merely experimenting did the damage. Please, consider that many idiots like me can destroy their servers without meaning it... and consuming more bandwidth is way more acceptable as a drawback compared to destroying the server files due to unwanted updates.
